repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.20.0
    hooks:
      - id: stylua

  - repo: local
    hooks:
      - id: nixfmt-classic
        name: nixfmt-classic
        entry: nix
        args: ["run", "nixpkgs#nixfmt-classic", "--"]
        language: system
        files: \.nix$
        pass_filenames: true

  - repo: local
    hooks:
      - id: flake-check
        name: nix flake check
        entry: nix
        args: ["flake", "check"]
        language: system
        files: ^flake\.(nix|lock)$
        pass_filenames: false
